razor-data-tools/Pages/Tools/ASCAP_Earnings.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor_data_tools.Utils;

namespace razor_data_tools.Pages.Tools
{
    public class ASCAP_EarningsModel : PageModel
    {
        [BindProperty]
        public int[] ImportedCount { get; set; } = new int[0];
        [BindProperty]
        public string[] ImportedFile { get; set; } = new string[0];

        [BindProperty]
        public List<Models.FileProperty> ImportedFileProperties { get; set; }

        public void OnGet()
        {

        }

        public void OnPostFileUpload(IFormFile[] files)
        {
            //TODO:  Determine what type of file - Old or New - then adjust the array columns as necessary
            int importedRecordCount = 0;
            int counter = 0;
            if (files != null && files.Length > 0)
                try
                {

                    foreach (var file in files)
                    {
                        string importFileName = file.FileName;
                        
                        



                        using (var stream = new MemoryStream())
                        {
                            file.CopyTo(stream);
                            
                            //await file.CopyToAsync(stream);
                            stream.Position = 0;
                            importedRecordCount = Utils.Csv.ImportASCAPEarningsCsvAndInsertIntoDatabase(stream, importFileName);
                            //append the filename and amount of records imported to their arrays
                            //TODO ADD FILE PROP INFO HERE
                            //_customerItems.Add(new SelectListItem(customer.PARTICIPANT_NAME, customer.PARTICIPANT_NUM));
                            ImportedFileProperties.Add(General.FactoryFileProperties(importFileName, importedRecordCount));

                            //increment the counter
                            counter++;
                            TempData["SuccessMessage"] = "File uploaded successfully. The page is ready for another upload.";
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    TempData["SuccessMessage"] = "There was an issue uploading the file.  Please contact support with this message:  " + ex.ToString();

                    //Message = "Error while parsing the file. Check the column order and format.";
                    //return Page();
                }

            //return RedirectToPage("./Index");

            //Message = "File has been processed.";
        }





       
    }
}

razor-data-tools/Pages/Tools/ASCAP_Earnings_Export.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using razor_data_tools.Models;
using razor_data_tools.Utils;

namespace razor_data_tools.Pages.Tools
{
    public class ASCAP_Earnings_ExportModel : PageModel
    {
        //list containing the select items bound OnGet
        private List<SelectListItem> _customerItems { get; set; }
        //The selectlist that will be filled with CustomerItems and bound to the control on the page with Model.Customers
        public SelectList Customers { get; set; }
        //property to receive the selected value
        [BindProperty(SupportsGet = true)]
        public string sSelectedCustomer { get; set; }

        //constructor
        public ASCAP_Earnings_ExportModel()
        {
            _customerItems = new List<SelectListItem>();
            List<ASCAP_Earnings_Customer> ListOfEarningsCustomers = General.ConvertASCAPCustomerToList(Data.Services.SelectAllASCAPEarningsParticipantNameAndNumber());

            //Loop through the customers and create the select list
            foreach (var customer in ListOfEarningsCustomers)
            {
                _customerItems.Add(new SelectListItem(customer.Party_Name, customer.Party_Id));

            }
        }



        public void OnGet()
        {
            Customers = new SelectList(_customerItems, "Value", "Text");
        }

        public ActionResult OnPostFileDownload()
        {
            string sParticipantNum = sSelectedCustomer;
            return DownloadCsv(sParticipantNum);
        }



        public FileResult DownloadCsv(string sParticipantNum)
        {

            var lstData = Utils.General.ConvertASCAPDataTableToList(Data.Services.SelectASCAPEarnings(sParticipantNum));
            var sb = new StringBuilder();
            sb.AppendLine("File_Type ,Statement_Recipient_Name ,Statement_Recipient_ID ,Party_Name ,Party_ID ,Legal_Earner_Party_ID ,Legal_Earner_Party_Name ,Distribution_Date ,Distribution_Year" +
                            ", Distribution_Quarter, File_Distribution_Year, File_Distribution_Quarter, Country_Name, Licensor, Licensor_Code, Performance_Start_Date, Performance_End_Date, Duration, Number_of_Plays" +
                            ", Work_Title, Work_ID, Member_Share, Series_Name, Program_Name, Dollar_GENERAL, Dollar_RADIO, Dollar_TV, Dollar_TV_FILM, Dollar_CINEMA, Dollar_TOTAL, Revenue_Class_Code" +
                            ", Revenue_Class_Description, Adjustment_Distribution_Date, Adjustment_Indicator, Adjustment_Reason_Code, Role_Type, Type_Of_Right, Territory, Performance_Source, Music_User, Network_Service" +
                            ", Survey_Type, Day_Part_Code, CA_Pct, Classification_Code, Performance_Type, Performing_Artist, Composer_Name, EE_Share, Credits, Premium_Credits, Premium_Dollars, Original_Distribution_Date ");
            foreach (var data in lstData)
            {
                sb.AppendLine(data.File_Type + "," +
                                data.Statement_Recipient_Name + "," +
                                data.Statement_Recipient_ID + "," +
                                data.Party_Name + "," +
                                data.Party_ID + "," +
                                data.Legal_Earner_Party_ID + "," +
                                data.Legal_Earner_Party_Name + "," +
                                data.Distribution_Date + "," +
                                data.Distribution_Year + "," +
                                data.Distribution_Quarter + "," +
                                data.File_Distribution_Year + "," +
                                data.File_Distribution_Quarter + "," +
                                data.Country_Name + "," +
                                data.Licensor + "," +
                                data.Licensor_Code + "," +
                                data.Performance_Start_Date + "," +
                                data.Performance_End_Date + "," +
                                data.Duration + "," +
                                data.Number_of_Plays + "," +
                                "\"" + data.Work_Title + "\"" +"," +
                                data.Work_ID + "," +
                                data.Member_Share + "," +
                                data.Series_Name + "," +
                                data.Program_Name + "," +
                                data.Dollar_GENERAL + "," +
                                data.Dollar_RADIO + "," +
                                data.Dollar_TV + "," +
                                data.Dollar_TV_FILM + "," +
                                data.Dollar_CINEMA + "," +
                                data.Dollar_TOTAL + "," +
                                data.Revenue_Class_Code + "," +
                                data.Revenue_Class_Description + "," +
                                data.Adjustment_Distribution_Date + "," +
                                data.Adjustment_Indicator + "," +
                                data.Adjustment_Reason_Code + "," +
                                data.Role_Type + "," +
                                data.Type_Of_Right + "," +
                                data.Territory + "," +
                                data.Performance_Source + "," +
                                data.Music_User + "," +
                                data.Network_Service + "," +
                                data.Survey_Type + "," +
                                data.Day_Part_Code + "," +
                                data.CA_Pct + "," +
                                data.Classification_Code + "," +
                                data.Performance_Type + "," +
                                data.Performing_Artist + "," +
                                data.Composer_Name + "," +
                                data.EE_Share + "," +
                                data.Credits + "," +
                                data.Premium_Credits + "," +
                                data.Premium_Dollars + "," +
                                data.Original_Distribution_Date);

            }
            //Message = "Returning File...";
            byte[] bytes = ASCIIEncoding.ASCII.GetBytes(sb.ToString());

            return File(bytes, "text/csv", "export.csv");

        }
    }
}

razor-data-tools/Pages/Tools/ASCAP_Earnings_Import.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor_data_tools.Utils;

namespace razor_data_tools.Pages.Tools
{
    public class ASCAP_Earnings_ImportModel : PageModel
    {

        [BindProperty]
        public int[] ImportedCount { get; set; } = new int[0];
        [BindProperty]
        public string[] ImportedFile { get; set; } = new string[0];

        [BindProperty]
        public List<Models.FileProperty> ImportedFileProperties { get; set; }

        public void OnGet()
        {

        }

        public void OnPostFileUpload(IFormFile[] files)
        {

            int importedRecordCount = 0;
            int counter = 0;
            if (files != null && files.Length > 0)
                try
                {

                    foreach (var file in files)
                    {
                        string importFileName = file.FileName;

                        using (var stream = new MemoryStream())
                        {
                            file.CopyTo(stream);
                            //await file.CopyToAsync(stream);
                            stream.Position = 0;
                            importedRecordCount = Utils.Csv.ImportASCAPEarningsCsvAndInsertIntoDatabase(stream, importFileName);
                            //append the filename and amount of records imported to their arrays
                            //TODO ADD FILE PROP INFO HERE
                            //_customerItems.Add(new SelectListItem(customer.PARTICIPANT_NAME, customer.PARTICIPANT_NUM));
                            ImportedFileProperties.Add(General.FactoryFileProperties(importFileName, importedRecordCount));

                            //increment the counter
                            counter++;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    //Message = "Error while parsing the file. Check the column order and format.";
                    //return Page();
                }

            //return RedirectToPage("./Index");

            //Message = "File has been processed.";
        }
    }
}

razor-data-tools/Pages/Tools/ASCAP_Works.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor_data_tools.Utils;

namespace razor_data_tools.Pages.Tools
{
    public class ASCAP_WorksModel : PageModel
    {

        [BindProperty]
        public int[] ImportedCount { get; set; } = new int[0];
        [BindProperty]
        public string[] ImportedFile { get; set; } = new string[0];

        [BindProperty]
        public List<Models.FileProperty> ImportedFileProperties { get; set; }

        public void OnGet()
        {
        }


        public void OnPostFileUpload(IFormFile[] files)
        {
            //TODO:  Determine what type of file - Old or New - then adjust the array columns as necessary
            int importedRecordCount = 0;
            int counter = 0;
            if (files != null && files.Length > 0)
                try
                {

                    foreach (var file in files)
                    {
                        string importFileName = file.FileName;

                        using (var stream = new MemoryStream())
                        {
                            file.CopyTo(stream);
                            //await file.CopyToAsync(stream);
                            stream.Position = 0;
                            importedRecordCount = Utils.Csv.ImportASCAPWorksCsvAndInsertIntoDatabase(stream, importFileName);
                            //append the filename and amount of records imported to their arrays

                            //TODO ADD FILE PROP INFO HERE

                            //_customerItems.Add(new SelectListItem(customer.PARTICIPANT_NAME, customer.PARTICIPANT_NUM));
                            ImportedFileProperties.Add(General.FactoryFileProperties(importFileName, importedRecordCount));

                            //increment the counter
                            counter++;
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    //Message = "Error while parsing the file. Check the column order and format.";
                    //return Page();
                }

            //return RedirectToPage("./Index");

            //Message = "File has been processed.";
        }



    }
}

razor-data-tools/Pages/Tools/BMI_Earnings_Import.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;

using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using razor_data_tools.Utils;


namespace razor_data_tools.Pages.Tools
{
    public class BMI_Earnings_ImportModel : PageModel
    {

        
        [BindProperty]
        public int[] ImportedCount { get; set; } = new int[0];
        [BindProperty]
        public string[] ImportedFile { get; set; } = new string[0];

        [BindProperty]
        public List<Models.FileProperty> ImportedFileProperties { get; set; }

        public void OnGet()
        {

        }

        public void OnPostFileUpload(IFormFile[] files)
        {
            
            int importedRecordCount = 0;
            int counter = 0;
            if (files != null && files.Length > 0)
                try
                {

                    foreach (var file in files)
                    {
                        string importFileName = file.FileName;

                        using (var stream = new MemoryStream())
                        {
                            file.CopyTo(stream);
                            //await file.CopyToAsync(stream);
                            stream.Position = 0;
                            importedRecordCount = Utils.Csv.ImportBMIEarningsCsvAndInsertIntoDatabase(stream, importFileName);
                            //append the filename and amount of records imported to their arrays
                            //TODO ADD FILE PROP INFO HERE
                            //_customerItems.Add(new SelectListItem(customer.PARTICIPANT_NAME, customer.PARTICIPANT_NUM));
                            ImportedFileProperties.Add(General.FactoryFileProperties(importFileName, importedRecordCount));

                            //increment the counter
                            counter++;
                            TempData["SuccessMessage"] = "File uploaded successfully. The page is ready for another upload.";
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    TempData["SuccessMessage"] = "There was an issue uploading the file.  Please contact support with this message:  " + ex.ToString();

                    //Message = "Error while parsing the file. Check the column order and format.";
                    //return Page();
                }

            //return RedirectToPage("./Index");

            //Message = "File has been processed.";
        }



    }
}

razor-data-tools/Pages/Tools/Tunecore.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace razor_data_tools.Pages.Tools
{
    public class TunecoreModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

razor-data-tools/Pages/Tools/ASCAP_Earnings.cshtml
@page
@model razor_data_tools.Pages.Tools.ASCAP_EarningsModel
@{

}

<script type="text/javascript">function DisplayMessage() {
        var x = document.getElementById("divMsg");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }</script>



<form class="form-horizontal" method="post" enctype="multipart/form-data">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }



    <div class="form-group">
        <h1 class="h2">Import ASCAP International Earnings csv data to database</h1>

        <div class="col-sm-10">
            <input type="file" name="files" accept=".csv" multiple />
            
            <input asp-page-handler="FileUpload" type="submit" value="Import" onClick="DisplayMessage()" />

            <div id="divMsg" style="font-size:x-large;display:none;">
                Processing Data. Please stay on page until processing is complete...
            </div>

            <p>
                @if (Model != null && Model.ImportedFileProperties != null)
                {

                    <table class="table">

                        <tr>
                            <th>File</th>
                            <th># Imported</th>
                        </tr>

                        @foreach (var importedFile in Model.ImportedFileProperties)
                        {
                            <tr>
                                <td>@importedFile.FileName</td>
                                <td>@importedFile.RecordCount.ToString()</td>
                            </tr>
                        }
                        <tr>
                            <td colspan="2">Processing is complete.</td>
                        </tr>
                    </table>
                }

            </p>
        </div>
    </div>
</form>

@section Scripts {
    <script>document.getElementById("SelectedArtist").addEventListener("change", function () {
            var display = this.value === "New Artist" ? "block" : "none";
            document.getElementById("NewArtistNameGroup").style.display = display;
        });</script>
}

razor-data-tools/Pages/Tools/ASCAP_Earnings_Export.cshtml
@page
@model razor_data_tools.Pages.Tools.ASCAP_Earnings_ExportModel
@{

}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <h1 class="h2">Export formatted csv data for ASCAP Affiliate</h1>
        <div class="col-sm-10">
            <label>Choose a name to download formatted earnings:</label>
            <select name="sSelectedCustomer" asp-items="Model.Customers">
                <option value="">Choose a customer</option>
            </select>
            <input asp-page-handler="FileDownload" type="submit" value="Export" />
        </div>

    </div>


</form>

razor-data-tools/Pages/Tools/ASCAP_Works.cshtml
@page
@model razor_data_tools.Pages.Tools.ASCAP_WorksModel
@{
}

<script type="text/javascript">function DisplayMessage() {
        var x = document.getElementById("divMsg");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }</script>



<form class="form-horizontal" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <h1 class="h2">Import ASCAP Works csv data to the database</h1>

        <div class="col-sm-10">
            <input type="file" name="files" accept=".csv" multiple />
            
            <input asp-page-handler="FileUpload" type="submit" value="Import" onClick="DisplayMessage()" />

            <div id="divMsg" style="font-size:x-large;display:none;">
                Processing Data. Please stay on page until processing is complete...
            </div>

            <p>
                @if (Model != null && Model.ImportedFileProperties != null)
                {

                    <table class="table">

                        <tr>
                            <th>File</th>
                            <th># Imported</th>
                        </tr>

                        @foreach (var importedFile in Model.ImportedFileProperties)
                        {
                            <tr>
                                <td>@importedFile.FileName</td>
                                <td>@importedFile.RecordCount.ToString()</td>
                            </tr>
                        }
                        <tr>
                            <td colspan="2">Processing is complete.</td>
                        </tr>
                    </table>
                }

            </p>
        </div>
    </div>
</form>

razor-data-tools/Pages/Tools/BMI_Earnings_Export.cshtml
@page
@model razor_data_tools.Pages.Tools.BMI_Earnings_ExportModel
@{

}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <h1 class="h2">Export formatted csv data for BMI Affiliate</h1>
        <div class="col-sm-10">
            <label>Choose a name to download formatted earnings:</label>
            <select name="sSelectedCustomer" asp-items="Model.Customers">
                <option value="">Choose a customer</option>
            </select>
            <input asp-page-handler="FileDownload" type="submit" value="Export" />
        </div>

    </div>

    
</form>

razor-data-tools/Pages/Tools/BMI_Earnings_Import.cshtml
@page
@model razor_data_tools.Pages.Tools.BMI_Earnings_ImportModel
@{

}

<script type="text/javascript">function DisplayMessage() {
        var x = document.getElementById("divMsg");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }</script>


<form class="form-horizontal" method="post" enctype="multipart/form-data">

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }

    <div class="form-group">
        <h1 class="h2">Import BMI Earnings csv data to database</h1>

        <div class="col-sm-10">
            <input type="file" name="files" accept=".csv" multiple />
            
            <input asp-page-handler="FileUpload" type="submit" value="Import" onClick="DisplayMessage()" />

            <div id="divMsg" style="font-size:x-large;display:none;">
                Processing Data. Please stay on page until processing is complete...
            </div>

            <p>
                @if (Model != null && Model.ImportedFileProperties != null)
                {

                    <table class="table">

                        <tr>
                            <th>File</th>
                            <th># Imported</th>
                        </tr>

                        @foreach (var importedFile in Model.ImportedFileProperties)
                        {
                            <tr>
                                <td>@importedFile.FileName</td>
                                <td>@importedFile.RecordCount.ToString()</td>
                            </tr>
                        }
                        <tr>
                            <td colspan="2">Processing is complete.</td>
                        </tr>
                    </table>
                }

            </p>
        </div>
    </div>
</form>
@section Scripts {
    <script>document.getElementById("SelectedArtist").addEventListener("change", function () {
            var display = this.value === "New Artist" ? "block" : "none";
            document.getElementById("NewArtistNameGroup").style.display = display;
        });</script>
}

razor-data-tools/Pages/Tools/PayorSelector.cshtml
@page
@model razor_data_tools.Pages.Tools.PayorSelectorModel
@{
}

<form method="post">
    <div>
        <label for="dropdown">Select an option:</label>
        <select id="dropdown" asp-for="SelectedOption">
            @foreach (var option in Model.Options)
            {
                <option value="@option.Value">@option.Text</option>
            }
        </select>
    </div>
    <div>
        <label for="textBox1">Textbox 1:</label>
        <input id="textBox1" type="date" asp-for="TextBox1Value" />
    </div>
    <div>
        <label for="textBox2">Textbox 2:</label>
        <input id="textBox2" type="date" asp-for="TextBox2Value" />
    </div>
    <button type="submit">Submit</button>
</form>

razor-data-tools/Pages/Tools/Tunecore_Earnings_Export.cshtml
@page
@model razor_data_tools.Pages.Tools.Tunecore_Earnings_ExportModel
@{

}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <h1 class="h2">Export formatted csv data for Tunecore Affiliate</h1>
        <div class="col-sm-10">
            <label>Choose a name to download formatted earnings:</label>
            <select name="sSelectedCustomer" asp-items="Model.Customers">
                <option value="">Choose a customer</option>
            </select>
            <input asp-page-handler="FileDownload" type="submit" value="Export" />
        </div>

    </div>


</form>

razor-data-tools/Pages/Tools/Tunecore_Earnings_Import.cshtml
@page
@model razor_data_tools.Pages.Tools.Tunecore_Earnings_ImportModel
@{

}

<script type="text/javascript">
        function DisplayMessage() {
            var x = document.getElementById("divMsg");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
</script>


<form class="form-horizontal" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <h1 class="h2">Import Tunecore Earnings csv data to database</h1>

        <div class="col-sm-10">
            <input type="file" name="files" accept=".csv" multiple />
          
            <input asp-page-handler="FileUpload" type="submit" value="Import" onClick="DisplayMessage()" />

            <div id="divMsg" style="font-size:x-large;display:none;">
                Processing Data. Please stay on page until processing is complete...
            </div>

            <p>
                @if (Model != null && Model.ImportedFileProperties != null)
                {
                    <table class="table">

                        <tr>
                            <th>File</th>
                            <th># Imported</th>
                        </tr>

                        @foreach (var importedFile in Model.ImportedFileProperties)
                        {
                            <tr>
                                <td>@importedFile.FileName</td>
                                <td>@importedFile.RecordCount.ToString()</td>
                            </tr>
                         }
                        <tr>
                            <td colspan="2">Processing is complete.</td>
                        </tr>

                    </table>
                    }

          
        </div>
    </div>
</form>

razor-data-tools/Pages/Tools/Tunecore_Earnings_Import_2.cshtml
@page
@model razor_data_tools.Pages.Tools.Tunecore_Earnings_Import_2Model
@{
}

<script type="text/javascript">function DisplayMessage() {
        var x = document.getElementById("divMsg");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }</script>


<h2>Upload File</h2>

<form method="post" enctype="multipart/form-data">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
        </div>
    }


    <div>
        <label for="ArtistDropdown">Choose Artist to upload files or Create a new artist:</label>
        <select asp-for="SelectedArtist" asp-items="Model.Artists">
            <option value="">Please select an artist</option>
        </select>
    </div>

    <div id="NewArtistNameGroup" style="display:none;">
        <label for="NewArtistName">New Artist Name (Format - LASTNAME FIRSTNAME [no commas or punctuation]):</label>
        <input asp-for="NewArtistName" class="form-control" style="width: 450px;" />
    </div>

    <div>
        <label for="files">File:</label>
        <input type="file" name="files" accept=".csv" multiple />
    </div>
   
    <input asp-page-handler="FileUpload" type="submit" value="Import" onClick="DisplayMessage()" />

    <div id="divMsg" style="font-size:x-large;display:none;">
        Processing Data. Please stay on page until processing is complete...
    </div>

    <p>
        @if (Model != null && Model.ImportedFileProperties != null)
        {

            <table class="table">

                <tr>
                    <th>File</th>
                    <th># Imported</th>
                </tr>

                @foreach (var importedFile in Model.ImportedFileProperties)
                {
                    <tr>
                        <td>@importedFile.FileName</td>
                        <td>@importedFile.RecordCount.ToString()</td>
                    </tr>
                }
                <tr>
                    <td colspan="2">Processing is complete.</td>
                </tr>
            </table>
        }

    </p>

</form>

@section Scripts {
    <script>document.getElementById("SelectedArtist").addEventListener("change", function() {
            var display = this.value === "New Artist" ? "block" : "none";
            document.getElementById("NewArtistNameGroup").style.display = display;
        });</script>
}